#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
  resource: .
  type: uploader

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /fr
    permanent: true

