#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
  resource: .
  type: uploader

controllers:
  resource: '../src/Controller/'
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'