#index:
#    path: /
#    controller: App\Controller\DefaultController::index



oneup_uploader:
  resource: .
  type: uploader

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /fr
    permanent: true

