easy_admin:
    entities:
        # List the entity class name you want to manage
        Utilisateurs:
            class: App\Entity\User
            form:
                fields:
                    - 'username'
                    - 'email'
                    - 'adresses'
                    - 'Galery'
                    - 'roles'

        Adress:
            class: App\Entity\Adress

        Galery:
            class: App\Entity\Galery

        Photo:
            class: App\Entity\Photo

        LivreDOr:
            class: App\Entity\LivreDOr

        Commande:
            class: App\Entity\Commande

        SitePhoto:
            class: App\Entity\SitePhoto

        SiteText:
            class: App\Entity\SiteText

        Organigramme:
            class:  App\Entity\Organigrame

    design:
        templates:
            layout: 'bundles/admin/layout.html.twig'