easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            form:
                fields:
                    - 'username'
                    - 'email'
                    - 'adresses'
                    - 'Galery'
        Adress:
            class: App\Entity\Adress
            form :
                fields :
                    - 'Nom'
                    - 'Prenom'
                    - 'Tel'
                    - 'Number'
                    - 'adress_1'
                    - 'adress_2'
                    - 'CP'
                    - 'City'
                    - 'User'

        Galery:
            class: App\Entity\Galery

        Photo:
            class: App\Entity\Photo

        LivreDOr:
            class: App\Entity\LivreDOr

        Commande:
            class: App\Entity\Commande
            form:
                fields:
                    - 'Statut'
                    - 'User'

        SitePhoto:
            class: App\Entity\SitePhoto

        SiteText:
            class: App\Entity\SiteText

    design:
        templates:
            layout: 'bundles/admin/layout.html.twig'
