fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: '%env(resolve:USER_ADDRESS)%'
    sender_name: '%env(resolve:SENDER_NAME)%'
  registration:
    form:
      type: App\Form\RegistrationType
framework:
  templating:
    engines: ['twig', 'php']
  session:
    cookie_secure: false
